config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "auth/:provider/callback", to: "sessions#create"
  get "signin", to: "sessions#new", as: "signin"

  post "/upcs" => "dvds#upc", as: "upcs"

  resources :auth, only: :show
  resources :sessions, only: [:destroy, :new]
  resources :users do
    resources :dvds
  end

  namespace :api do
    namespace :v1 do
      resources :dvds
      post "/upcs" => "dvds#upc", as: "upcs"
    end
  end
end

app/models/dvd.rb
class Dvd <ApplicationRecord
  belongs_to :user
  belongs_to :upc
  belongs_to :location, required: false
  accepts_nested_attributes_for :location

  validates :upc, presence: true
  validates :user, presence: true
  validates :title, presence: true
  validates :user_rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 5, message: "must be between 1 - 5"}, allow_nil: true
  validates :mpaa_rating, inclusion: { in: ["G (General Audience)", "G", "PG (Parental Guidance Suggested)", "PG", "PG-13 (Parental Guidance Suggested)", "PG-13 (Parents Strongly Cautioned)", "PG-13", "R (Restricted)", "R", "NC-17", "X", "NR (Not Rated)", "NR", "Unrated", "Unrated (Not Rated)"], message: "%{value} is not a valid rating" }, allow_nil: true

  def self.search(query)
    where("title ilike ?", "%#{query}%")
  end
end

app/controllers/api/v1/dvds_controller.rb
class Api::V1::DvdsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @dvd = Dvd.all
    render json: { dvds: @dvd }
  end

  def upc
    if !Upc.where(upc: params[:upc]).empty?
      @upc = Upc.where(upc: params[:upc]).first
    else
      @upc = Upc.create(upc: params[:upc])
    end
    @error = ErrorObject.new
    @dvd = Dvd.new
    @dvd.upc = @upc
    populate_form(@dvd, @error)

    render json: {dvd: @dvd, upc: @upc, error: @error}
  end

  def create
    @error = ErrorObject.new
    @dvd = Dvd.new(dvd_params)
    @dvd.user = current_user
    add_images(@dvd)
    if @dvd.mpaa_rating == ""
      @dvd.mpaa_rating = nil
    end

    if @dvd.save
      flash[:notice] = "DVD added!"
      redirect_to "/users/#{current_user.id}/dvds"
    else
      @error.state = true
      @error.message = @dvd.errors.full_messages.to_sentence
      @upc = @dvd.upc

      render json: {dvd: @dvd, upc: @upc, error: @error}
    end
  end

  private

  def dvd_params
    params.require(:dvd).permit(:upc_id, :title, :purchase_price, :location_id, :user_rating, :mpaa_rating, :synopsis, :studio, :cast, :writer, :producer, :director, :release_date, :run_time)
  end

  def populate_form(dvd_object, error_object)
    data = AmazonHelper.new(dvd_object.upc.upc)
    if data.error
      error_object.state = true
      error_object.message = data.error_message
    else
      dvd_object.title = data.title
      dvd_object.mpaa_rating = data.mpaa
      dvd_object.synopsis = data.synopsis
      dvd_object.studio = data.studio
      dvd_object.cast = data.cast
      dvd_object.writer = data.writer
      dvd_object.producer = data.producer
      dvd_object.director = data.director
      dvd_object.release_date = data.release_date
      dvd_object.run_time = data.run_time
    end
    dvd_object
  end

  def add_images(dvd_object)
    data = AmazonHelper.new(dvd_object.upc.upc)
    dvd_object.image_small = data.small_image
    dvd_object.image_large = data.large_image
    dvd_object
  end

end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])

    @user_can_change = false
    unless current_user.nil?
      @user_can_change = can_change?(@user)
    end

    if params[:search]
      @query = params[:search]
      @dvds = @user.dvds.search(@query).order("created_at DESC")
    else
      @dvds = @user.dvds
    end
  end

  def show
    @user = User.find(params[:user_id])
    @dvd = Dvd.find(params[:id])

    @user_can_change = false
    unless current_user.nil?
      @user_can_change = can_change?(@user)
    end
  end

  def new
    @user = current_user
    @location = Location.new
    @dvd = Dvd.new
    @dvd.location = @location
    @upc = Upc.new
    @submit_text = "Add DVD"
    @path = user_dvds_path(current_user)
  end

  def create
    @dvd = Dvd.new(dvd_params)
    @dvd.user = current_user
    add_images(@dvd)
    if @dvd.mpaa_rating == ""
      @dvd.mpaa_rating = nil
    end

    if @dvd.save
      flash[:notice] = "DVD added!"
      redirect_to user_dvds_path(current_user)
    else
      flash[:notice] = @dvd.errors.full_messages.to_sentence
      @upc = @dvd.upc
      newupc = Upc.new
      newupc.upc = @upc.upc
      @upc = newupc
      @submit_text = "Add DVD"
      @path = user_dvds_path(current_user)

      render :new
    end
  end

  def upc
    if !Upc.where(upc: upc_params[:upc]).empty?
      @upc = Upc.where(upc: upc_params[:upc]).first
    else
      @upc = Upc.create(upc_params)
    end
    @dvd = Dvd.new
    @dvd.upc = @upc
    populate_form(@dvd)
    newupc = Upc.new
    newupc.upc = @upc.upc
    @upc = newupc
    @submit_text = "Add DVD"
    @path = user_dvds_path(current_user)

    render :new
  end

  def edit
    @user = current_user
    @title = Dvd.find(params[:id]).title
    @dvd = Dvd.find(params[:id])
    @submit_text = "Save"
    @path = user_dvd_path(current_user, @dvd)

    unless can_change?(User.find(params[:user_id]))
      raise ActionController::RoutingError.new("Not Found")
    end

    @delete = true
  end

  def update
    @dvd = Dvd.find(params[:id])

    unless can_change?(User.find(params[:user_id]))
      raise ActionController::RoutingError.new("Not Found")
    end

    if @dvd.update(dvd_params)
      flash[:notice] = "Edits Saved"
      redirect_to @dvd
    else
      @delete = true
      @title = Dvd.find(params[:id]).title
      flash[:notice] = @dvd.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @dvd = Dvd.find(params[:id])
    @dvd.destroy
    redirect_to user_dvds_path(current_user)
  end

  private

  def dvd_params
    params.require(:dvd).permit(:upc_id, :title, :purchase_price, :location_id, :user_rating, :mpaa_rating, :synopsis, :studio, :cast, :writer, :producer, :director, :release_date, :run_time)
  end

  def upc_params
    params.require(:upc).permit(:upc)
  end

  def can_change?(user)
    current_user == user
  end

  def populate_form(dvd_object)
    data = AmazonHelper.new(dvd_object.upc.upc)
    if data.error
      flash[:notice] = data.error_message
    else
      dvd_object.title = data.title
      dvd_object.mpaa_rating = data.mpaa
      dvd_object.synopsis = data.synopsis
      dvd_object.studio = data.studio
      dvd_object.cast = data.cast
      dvd_object.writer = data.writer
      dvd_object.producer = data.producer
      dvd_object.director = data.director
      dvd_object.release_date = data.release_date
      dvd_object.run_time = data.run_time
    end
    dvd_object
  end

  def add_images(dvd_object)
    data = AmazonHelper.new(dvd_object.upc.upc)
    dvd_object.image_small = data.small_image
    dvd_object.image_large = data.large_image
    dvd_object
  end
end

app/views/dvds/_form.html.erb
<%= form_for [@user, @dvd] do |f| %>
  <div class="small-12 medium-6 column">
    <%= f.label :purchase_price %>
    <%= f.text_field :purchase_price %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :location_id %>
    <%= f.collection_select(:location_id, @user.locations, :id, :name) %>
  </div>

  <div class="small-12 column">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="small-12 column">
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis, size: "60x10" %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :user_rating %>
    <%= f.text_field :user_rating %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :mpaa_rating, "MPAA Rating" %>
    <%= f.text_field :mpaa_rating %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :cast %>
    <%= f.text_field :cast %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :writer %>
    <%= f.text_field :writer %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :producer %>
    <%= f.text_field :producer %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :release_date %>
    <%= f.text_field :release_date %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :run_time %>
    <%= f.text_field :run_time %>
  </div>

  <div class="small-12 medium-6 column">
    <%= f.label :studio %>
    <%= f.text_field :studio %>
  </div>

  <div class="small-12 column" id="dvd_submit">
    <% if !params[:upc].nil? %>
      <%= f.hidden_field :upc_id, value: Upc.find_by(upc: params[:upc][:upc]).id %>
    <% end %>
    <br>
    <%= f.submit "#{@submit_text}", class: "button secondary" %>
    <% if @delete %>
      <%= link_to 'Delete', [@user, @dvd], method: :delete, data: { confirm: "Are you sure?" }, class: "button secondary" %>
    <% end %>
    <%= link_to 'Back', @path, class: "button secondary" %>
  </div>
<% end %>

app/views/dvds/edit.html.erb
<div class="dvd-content">
  <%= render 'layouts/navbar' %>
  <div class='content-box row'>
    <h1>Edit <%= @title %></h1>

    <%= render 'dvds/form' %>
  </div>
</div>

app/views/dvds/index.html.erb
<div class="dvd-content">
  <%= render 'layouts/navbar' %>
  <div class="content-box">
    <h1><%= @user.name %>'s DVDs</h1>
    <div class="row">
      <%= form_tag user_dvds_path(@user), :method => 'get' do %>
        <div class="small-10 columns">
          <%= text_field_tag :search, params[:search], placeholder: "Search Collection" %>
        </div>
        <div class="small-2 columns">
          <%= submit_tag "Search", name: nil, class: "button secondary" %>
        </div>
      <% end %>
    </div>
    <% if @user_can_change %>
      <%= link_to "Add a DVD", new_user_dvd_path(@user), class: "button secondary" %>
    <% end %>
  </div>

  <div class="itemList row small-up-1 medium-up-3 large-up-5">
    <% @dvds.each do |dvd| %>
      <% class_name = "column list-item-box" %>
      <% if dvd == @dvds.last %>
        <% class_name += " end" %>
      <% end %>
      <div key=<%= dvd.id %> class=<%= class_name %>>
        <%= link_to user_dvd_path(@user, dvd) do %>
          <div class="list-item-content">
            <p><%= dvd.title %></p>
            <div>
              <img src=<%= dvd.image_small %> alt="no image" class="index-item-image-box"/>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/dvds/new.html.erb
<div class="dvd-content" id=<%= @user.id.to_s %>>
  <%= render 'layouts/navbar' %>
  <div id="new_dvd" class="content-box row">
    <div class="row">
      <%= form_for(@upc) do |f| %>
        <div class="small-2 columns">
          <%= f.label :upc, "UPC" %>
        </div>
        <div class="small-8 columns"
          <%= f.text_field :upc %>
        </div>
        <div class="small-2 columns">
          <%= f.submit "Search UPC" %>
        </div>
      <% end %>
    </div>

    <%= render 'dvds/form' %>

  </div>
</div>

app/views/dvds/show.html.erb
<div class="dvd-content">
  <%= render 'layouts/navbar' %>
  <div class="content-box row">
    <h1><%= @dvd.title %> </h1>
    <div class="small-6 column text-left">
      <p><b>Synopsis:</b> <%= @dvd.synopsis %> </p>
      <p><b>Cast:</b> <%= @dvd.cast %> </p>
      <p><b>Director:</b> <%= @dvd.director %> </p>
      <p><b>Writer:</b> <%= @dvd.writer %> </p>
      <p><b>Producer:</b> <%= @dvd.producer %> </p>
      <p><b>Studio:</b> <%= @dvd.studio %> </p>
      <p><b>Rating:</b> <%= @dvd.mpaa_rating %> </p>
      <p><b>Movie Length:</b> <%= @dvd.run_time %> </p>
      <p><b>Dvd Release Date:</b> <%= @dvd.release_date %> </p>
      <p><b>Dvd Added:</b> <%= @dvd.created_at %> </p>
    </div>
    <div class="small-6 column">
      <img src=<%= @dvd.image_large %> />
      <div class="text-left">
        <p><b>User Rating:</b> <%= @dvd.user_rating %> </p>
        <p><b>Purchase Price:</b> <%= @dvd.purchase_price %> </p>
        <% if !@dvd.location.nil? %>
          <p><b>Purchase Location:</b> <%= @dvd.location.name %> </p>
        <% else %>
          <p><b>Purchase Location:</b></p>
        <% end %>
        <% if @user_can_change %>
          <%= link_to "Edit", edit_user_dvd_path(@user, @dvd), class: "button secondary" %>
          <%= link_to 'Delete', [@user, @dvd], method: :delete,
            data: { confirm: "Are you sure?" }, class: "button secondary" %>
        <% end %>
        <%= link_to "Back", user_dvds_path(@user), class: "button secondary" %>
      </div>
    </div>
  </div>
</div>-