config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "auth/:provider/callback", to: "sessions#create"
  get "signin", to: "sessions#new", as: "signin"

  post "/upcs" => "dvds#upc", as: "upcs"

  resources :auth, only: :show
  resources :sessions, only: [:destroy, :new]
  resources :users do
    resources :dvds
  end

  namespace :api do
    namespace :v1 do
      resources :dvds
      post "/upcs" => "dvds#upc", as: "upcs"
    end
  end
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="top-bar small-12 columns" data-topbar role="navigation">
    <ul class="title-area small-3 columns" >
      <li class="name">
        <h1><a href="/">MDVDM</a></h1>
      </li>
    </ul>

    <ul class="right">
      <li class='right-item nav-link account-settings'> <%= link_to 'Profile', user_path(current_user) %> </li>
      <li class='right-item nav-link sign-out'> <%= link_to 'Sign Out', session_path(current_user), :method => :delete %> </li>
    </ul>
  </nav>
<% end %>

<div class="top-bar-spacer"></div>

<div class='error-msgs'>
  <% flash.each do |name, msg| %>
    <div class='error-msg'>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div class='error'>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>MyDvdManager</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">
  </head>


  <body>
    <%= yield %>
  </body>
</html>